### ISSUE TITLE
Allow hashing a stream

### ISSUE THREAD

**Issue by cbenhagen** [SamJakob/xxh3#2]
The current implementation requires the whole data to be in memory. Allowing a `Stream<List<int>>` as an input would make it possible to hash big files.

**Comment by SamJakob** [comment]
Yes, agreed - that'd be ideal.

Does XXH3 work with streams? If so, do you know of any working implementations of this?

EDIT: found my answer to both; yes and yes. https://github.com/Cyan4973/xxHash/blob/dev/xxhash.h#L133
I'll start looking into this, but I have limited time available so I can't promise anything soon.

**Comment by SamJakob** [comment]
This should now be available in v1.2.0.

Documentation:

- https://pub.dev/documentation/xxh3/latest/topics/Stream%20API-topic.html
- https://pub.dev/documentation/xxh3/latest/xxh3/xxh3Stream.html
